const { getDb } = require('./db');

// ========== 模板 1：极简白 ==========
const TEMPLATE_MINIMAL = `<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{{name}} - 个人主页</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { 
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Helvetica Neue', sans-serif; 
      background: #ffffff; 
      color: #1a1a1a; 
      line-height: 1.6; 
    }
    .container { 
      max-width: 680px; 
      margin: 0 auto; 
      padding: 80px 24px; 
    }
    .header { margin-bottom: 64px; }
    .name { 
      font-size: 40px; 
      font-weight: 600; 
      letter-spacing: -0.02em; 
      margin-bottom: 8px; 
    }
    .title { 
      font-size: 18px; 
      color: #666; 
      font-weight: 400; 
    }
    .section { margin-bottom: 48px; }
    .section-title { 
      font-size: 12px; 
      text-transform: uppercase; 
      letter-spacing: 0.1em; 
      color: #999; 
      margin-bottom: 16px; 
    }
    .bio { 
      font-size: 16px; 
      color: #444; 
      line-height: 1.8; 
    }
    .contact-item { 
      font-size: 15px; 
      color: #555; 
      margin-bottom: 8px; 
    }
    .contact-item a { 
      color: #1a1a1a; 
      text-decoration: none; 
      border-bottom: 1px solid #ddd; 
    }
    .resume-link { 
      display: inline-block; 
      margin-top: 16px; 
      padding: 10px 24px; 
      border: 1px solid #1a1a1a; 
      color: #1a1a1a; 
      text-decoration: none; 
      font-size: 14px; 
      transition: all 0.2s; 
    }
    .resume-link:hover { 
      background: #1a1a1a; 
      color: #fff; 
    }
    .portfolio { 
      display: grid; 
      grid-template-columns: repeat(2, 1fr); 
      gap: 16px; 
    }
    .portfolio img { 
      width: 100%; 
      border-radius: 4px; 
    }
    .footer { 
      margin-top: 80px; 
      padding-top: 24px; 
      border-top: 1px solid #eee; 
      font-size: 12px; 
      color: #bbb; 
    }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1 class="name">{{name}}</h1>
      <p class="title">{{title}}</p>
    </div>
    
    <div class="section">
      <p class="section-title">About</p>
      <p class="bio">{{bio}}</p>
    </div>
    
    <div class="section">
      <p class="section-title">Contact</p>
      <p class="contact-item">{{email}}</p>
      <p class="contact-item">{{phone}}</p>
      {{RESUME_SECTION}}
    </div>
    
    {{PORTFOLIO_SECTION}}
    
    <div class="footer">
      <p>Generated by Profile Builder</p>
    </div>
  </div>
</body>
</html>`

// ========== 模板 2：深色科技 ==========
const TEMPLATE_DARK = `<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{{name}} - 个人主页</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { 
      font-family: 'Inter', -apple-system, sans-serif; 
      background: #0a0a0f; 
      color: #e0e0e0; 
      line-height: 1.6; 
    }
    .container { 
      max-width: 720px; 
      margin: 0 auto; 
      padding: 80px 24px; 
    }
    .header { 
      margin-bottom: 60px; 
      padding-bottom: 40px; 
      border-bottom: 1px solid #1f1f2e; 
    }
    .name { 
      font-size: 48px; 
      font-weight: 700; 
      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); 
      -webkit-background-clip: text; 
      -webkit-text-fill-color: transparent; 
      margin-bottom: 12px; 
    }
    .title { 
      font-size: 18px; 
      color: #888; 
    }
    .section { margin-bottom: 48px; }
    .section-title { 
      font-size: 13px; 
      font-weight: 600; 
      color: #667eea; 
      text-transform: uppercase; 
      letter-spacing: 0.15em; 
      margin-bottom: 20px; 
    }
    .bio { 
      font-size: 16px; 
      color: #b0b0b0; 
      line-height: 1.8; 
    }
    .contact-item { 
      font-size: 15px; 
      color: #999; 
      margin-bottom: 10px; 
    }
    .contact-item a { 
      color: #e0e0e0; 
      text-decoration: none; 
    }
    .resume-link { 
      display: inline-flex; 
      align-items: center; 
      gap: 8px; 
      margin-top: 20px; 
      padding: 12px 28px; 
      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); 
      color: #fff; 
      text-decoration: none; 
      border-radius: 8px; 
      font-size: 14px; 
      font-weight: 500; 
    }
    .portfolio { 
      display: grid; 
      grid-template-columns: repeat(2, 1fr); 
      gap: 20px; 
    }
    .portfolio-item { 
      position: relative; 
      border-radius: 12px; 
      overflow: hidden; 
      background: #1a1a2e; 
    }
    .portfolio-item img { 
      width: 100%; 
      display: block; 
      transition: transform 0.3s; 
    }
    .portfolio-item:hover img { 
      transform: scale(1.05); 
    }
    .footer { 
      margin-top: 80px; 
      padding-top: 24px; 
      border-top: 1px solid #1f1f2e; 
      font-size: 12px; 
      color: #555; 
      text-align: center; 
    }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1 class="name">{{name}}</h1>
      <p class="title">{{title}}</p>
    </div>
    
    <div class="section">
      <p class="section-title">About Me</p>
      <p class="bio">{{bio}}</p>
    </div>
    
    <div class="section">
      <p class="section-title">Get In Touch</p>
      <p class="contact-item">📧 {{email}}</p>
      <p class="contact-item">📱 {{phone}}</p>
      {{RESUME_SECTION}}
    </div>
    
    {{PORTFOLIO_SECTION}}
    
    <div class="footer">
      <p>Generated by Profile Builder</p>
    </div>
  </div>
</body>
</html>`

// ========== 模板 3：卡片暖色 ==========
const TEMPLATE_CARD = `<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{{name}} - 个人主页</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { 
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; 
      background: #faf6f1; 
      color: #3d3d3d; 
      line-height: 1.6; 
    }
    .container { 
      max-width: 700px; 
      margin: 0 auto; 
      padding: 60px 24px; 
    }
    .header { 
      background: #fff; 
      padding: 48px; 
      border-radius: 20px; 
      box-shadow: 0 4px 20px rgba(0,0,0,0.06); 
      margin-bottom: 32px; 
      text-align: center; 
    }
    .name { 
      font-size: 36px; 
      font-weight: 700; 
      color: #2c2c2c; 
      margin-bottom: 8px; 
    }
    .title { 
      font-size: 16px; 
      color: #c17817; 
      font-weight: 500; 
    }
    .card { 
      background: #fff; 
      padding: 32px; 
      border-radius: 16px; 
      box-shadow: 0 2px 12px rgba(0,0,0,0.04); 
      margin-bottom: 24px; 
    }
    .card-title { 
      font-size: 14px; 
      font-weight: 600; 
      color: #c17817; 
      text-transform: uppercase; 
      letter-spacing: 0.1em; 
      margin-bottom: 16px; 
      display: flex; 
      align-items: center; 
      gap: 8px; 
    }
    .bio { 
      font-size: 15px; 
      color: #555; 
      line-height: 1.8; 
    }
    .contact-item { 
      font-size: 15px; 
      color: #666; 
      margin-bottom: 10px; 
      padding: 8px 0; 
      border-bottom: 1px dashed #eee; 
    }
    .contact-item:last-child { 
      border-bottom: none; 
    }
    .resume-link { 
      display: inline-block; 
      margin-top: 12px; 
      padding: 12px 28px; 
      background: #c17817; 
      color: #fff; 
      text-decoration: none; 
      border-radius: 10px; 
      font-size: 14px; 
      font-weight: 500; 
      transition: background 0.2s; 
    }
    .resume-link:hover { 
      background: #a56514; 
    }
    .portfolio { 
      display: grid; 
      grid-template-columns: repeat(2, 1fr); 
      gap: 16px; 
    }
    .portfolio-item { 
      border-radius: 12px; 
      overflow: hidden; 
      box-shadow: 0 2px 8px rgba(0,0,0,0.08); 
    }
    .portfolio-item img { 
      width: 100%; 
      display: block; 
    }
    .footer { 
      text-align: center; 
      padding: 40px 0; 
      font-size: 12px; 
      color: #bbb; 
    }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1 class="name">{{name}}</h1>
      <p class="title">{{title}}</p>
    </div>
    
    <div class="card">
      <p class="card-title">📝 关于我</p>
      <p class="bio">{{bio}}</p>
    </div>
    
    <div class="card">
      <p class="card-title">📮 联系方式</p>
      <p class="contact-item">邮箱：{{email}}</p>
      <p class="contact-item">电话：{{phone}}</p>
      {{RESUME_SECTION}}
    </div>
    
    {{PORTFOLIO_SECTION}}
    
    <div class="footer">
      <p>Generated by Profile Builder</p>
    </div>
  </div>
</body>
</html>`

// 模板映射
const templateMap = {
  'template1': TEMPLATE_MINIMAL,
  'template2': TEMPLATE_DARK,
  'template3': TEMPLATE_CARD
}

module.exports = async (req, res) => {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
  
  if (req.method === 'OPTIONS') {
    return res.status(204).end();
  }

  try {
    let userId = req.query.userId || '';
    let subdomain = req.query.subdomain || '';

    const db = await getDb();
    const users = db.collection('users');

    let query = {};
    if (userId && subdomain) {
      query = { userId, subdomain };
    } else if (userId) {
      query = { userId };
    } else if (subdomain) {
      query = { subdomain };
    }

    const user = await users.findOne(query);

    if (!user) {
      return res.status(404).send(`<!DOCTYPE html>
<html>
<head><title>404</title></head>
<body style="font-family:Arial;text-align:center;padding:80px 20px;">
  <h1 style="font-size:72px;color:#ddd;margin-bottom:20px;">404</h1>
  <p style="font-size:18px;color:#666;">页面不存在</p>
  <p style="color:#999;">该用户尚未创建个人主页</p>
</body>
</html>`);
    }

    const template = templateMap[user.templateId] || templateMap['template1'];

    let html = template
      .replace(/{{name}}/g, user.name || '未命名')
      .replace(/{{title}}/g, user.title || '')
      .replace(/{{bio}}/g, user.bio || '')
      .replace(/{{email}}/g, user.email || '')
      .replace(/{{phone}}/g, user.phone || '');

    // 简历部分
    if (user.resumeUrl) {
      const filename = user.resumeFilename || '简历.pdf';
      html = html.replace(
        '{{RESUME_SECTION}}',
        `<a href="#" onclick="openPdf()" class="resume-link">📄 下载简历</a>
     <script>
       function openPdf() {
         const base64Url = '${user.resumeUrl}'
         const byteString = atob(base64Url.split(',')[1])
         const mimeString = base64Url.split(',')[0].split(':')[1].split(';')[0]
         const ab = new ArrayBuffer(byteString.length)
         const ia = new Uint8Array(ab)
         for (let i = 0; i < byteString.length; i++) {
           ia[i] = byteString.charCodeAt(i)
         }
         const blob = new Blob([ab], { type: mimeString })
         const url = URL.createObjectURL(blob)
         window.open(url, '_blank')
       }
     </script>`
      );
    } else {
      html = html.replace('{{RESUME_SECTION}}', '');
    }

    // 作品集部分
    if (user.portfolioUrls && user.portfolioUrls.length > 0) {
      const images = user.portfolioUrls.map(url =>
        `<div class="portfolio-item"><img src="${url}" alt="作品"></div>`
      ).join('');
      html = html.replace(
        '{{PORTFOLIO_SECTION}}',
        `<div class="section"><p class="section-title">Portfolio</p><div class="portfolio">${images}</div></div>`
      );
    } else {
      html = html.replace('{{PORTFOLIO_SECTION}}', '');
    }

    res.setHeader('Content-Type', 'text/html; charset=utf-8');
    return res.status(200).send(html);

  } catch (error) {
    console.log('getPage 错误:', error.message);
    return res.status(500).send(`<!DOCTYPE html>
<html>
<head><title>500</title></head>
<body style="font-family:Arial;text-align:center;padding:80px 20px;">
  <h1 style="font-size:72px;color:#ddd;margin-bottom:20px;">500</h1>
  <p style="font-size:18px;color:#666;">服务器错误</p>
  <p style="color:#999;">${error.message}</p>
</body>
</html>`);
  }
};